# Generated by Django 5.1 on 2024-09-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger_app', '0002_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
    ]
