# Generated by Django 5.1 on 2024-09-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_app', '0003_remove_contactmessage_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
