# Generated by Django 5.1 on 2024-09-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_app', '0005_rename_item_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(upload_to='menu_images/'),
        ),
    ]
