# Generated by Django 5.1 on 2024-09-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_app', '0008_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
