# Generated by Django 5.1 on 2024-09-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger_app', '0009_alter_menuitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
