# Generated by Django 5.1 on 2024-09-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger_app', '0013_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
