# Generated by Django 5.1 on 2024-09-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_app', '0014_remove_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
