# Generated by Django 5.1 on 2024-09-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger_app', '0016_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
